### ISSUE TITLE
Error due make

### ISSUE THREAD

**Issue by core01** [jeremyb31/bluetooth-4.4#1]
Hello, my OS is Elementary OS Loki:
I followed this comment https://elementaryos.stackexchange.com/a/12066
There is error due make:
```
core01@RS:~/bluetooth-4.4$ make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
make: Entering directory '/usr/src/linux-headers-4.13.0-36-generic'
  CC [M]  /home/core01/bluetooth-4.4/hci_vhci.o
/home/core01/bluetooth-4.4/hci_vhci.c: In function ‘__vhci_create_device’:
/home/core01/bluetooth-4.4/hci_vhci.c:103:18: error: ‘HCI_BREDR’ undeclared (first use in this function)
  if (dev_type != HCI_BREDR && dev_type != HCI_AMP)
                  ^
/home/core01/bluetooth-4.4/hci_vhci.c:103:18: note: each undeclared identifier is reported only once for each function it appears in
/home/core01/bluetooth-4.4/hci_vhci.c:149:2: warning: dereferencing ‘void *’ pointer
  *skb_put(skb, 1) = 0xff;
  ^
/home/core01/bluetooth-4.4/hci_vhci.c:149:2: error: invalid use of void expression
/home/core01/bluetooth-4.4/hci_vhci.c:150:2: warning: dereferencing ‘void *’ pointer
  *skb_put(skb, 1) = opcode;
  ^
/home/core01/bluetooth-4.4/hci_vhci.c:150:2: error: invalid use of void expression
/home/core01/bluetooth-4.4/hci_vhci.c: In function ‘vhci_open_timeout’:
/home/core01/bluetooth-4.4/hci_vhci.c:319:43: error: ‘HCI_BREDR’ undeclared (first use in this function)
  vhci_create_device(data, amp ? HCI_AMP : HCI_BREDR);
                                           ^
scripts/Makefile.build:315: recipe for target '/home/core01/bluetooth-4.4/hci_vhci.o' failed
make[1]: *** [/home/core01/bluetooth-4.4/hci_vhci.o] Error 1
Makefile:1550: recipe for target '_module_/home/core01/bluetooth-4.4' failed
make: *** [_module_/home/core01/bluetooth-4.4] Error 2
make: Leaving directory '/usr/src/linux-headers-4.13.0-36-generic'
core01@RS:~/bluetooth-4.4$
```

**Comment by jeremyb31** [comment]
4.4 bluetooth source code isn't meant to work with a 4.13 kernel

**Comment by Jessekalli** [comment]
have a solution for the 5.3 kernel?

**Comment by Jessekalli** [comment]
> Hello, my OS is Elementary OS Loki:
> I followed this comment https://elementaryos.stackexchange.com/a/12066
> There is error due make:
> 
> ```
> core01@RS:~/bluetooth-4.4$ make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
> make: Entering directory '/usr/src/linux-headers-4.13.0-36-generic'
>   CC [M]  /home/core01/bluetooth-4.4/hci_vhci.o
> /home/core01/bluetooth-4.4/hci_vhci.c: In function ‘__vhci_create_device’:
> /home/core01/bluetooth-4.4/hci_vhci.c:103:18: error: ‘HCI_BREDR’ undeclared (first use in this function)
>   if (dev_type != HCI_BREDR && dev_type != HCI_AMP)
>                   ^
> /home/core01/bluetooth-4.4/hci_vhci.c:103:18: note: each undeclared identifier is reported only once for each function it appears in
> /home/core01/bluetooth-4.4/hci_vhci.c:149:2: warning: dereferencing ‘void *’ pointer
>   *skb_put(skb, 1) = 0xff;
>   ^
> /home/core01/bluetooth-4.4/hci_vhci.c:149:2: error: invalid use of void expression
> /home/core01/bluetooth-4.4/hci_vhci.c:150:2: warning: dereferencing ‘void *’ pointer
>   *skb_put(skb, 1) = opcode;
>   ^
> /home/core01/bluetooth-4.4/hci_vhci.c:150:2: error: invalid use of void expression
> /home/core01/bluetooth-4.4/hci_vhci.c: In function ‘vhci_open_timeout’:
> /home/core01/bluetooth-4.4/hci_vhci.c:319:43: error: ‘HCI_BREDR’ undeclared (first use in this function)
>   vhci_create_device(data, amp ? HCI_AMP : HCI_BREDR);
>                                            ^
> scripts/Makefile.build:315: recipe for target '/home/core01/bluetooth-4.4/hci_vhci.o' failed
> make[1]: *** [/home/core01/bluetooth-4.4/hci_vhci.o] Error 1
> Makefile:1550: recipe for target '_module_/home/core01/bluetooth-4.4' failed
> make: *** [_module_/home/core01/bluetooth-4.4] Error 2
> make: Leaving directory '/usr/src/linux-headers-4.13.0-36-generic'
> core01@RS:~/bluetooth-4.4$
> ```

I have the same problem
My OS is Linux Mint Cinnamon

**Comment by jeremyb31** [comment]
Please ask a question on forums.linuxmint.com  I created this to fix an issue that existed for a short time with the 4.4 Ubuntu kernels that was fixed in the upstream kernels
